### PR TITLE
Replacing license to better bit project type.

### PR DESCRIPTION
**Pull request by dewan-ahmed**
Fix for https://github.com/dewan-ahmed/recruiter-response-template/issues/1

### CODE REVIEW

**Comment by mekkim** [comment]
CC0 is an attempt to relinquish copyright on the works entirely and put it in the "public domain", of sorts.  It's complex because it's trying to account for all the different international jurisdictions, some of which don't recognize the concept of public domain.  If this is your intention, then it's fine.  If you would prefer to keep the copyright as yours, but permit others to use some or most of your rights, then a different CC licence would be better.  It looks like Github does have other CC licenses available by default without the need to create a custom license: [https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by dewan-ahmed** [comment]
Screen Shot 2022-03-14 at 4 34 31 PM

@mekkim the license picker is not showing the other CC licenses.

**Comment by mekkim** [comment]
Odd. I'm not sure why since they're clearly listed in the Github docs.  Might have top do custom then.  Or leave it as CC0 or go back to Apache.  Up to you.  Silly Github.

**Comment by dewan-ahmed** [comment]
I wonder if I can copy-paste the license found here: https://creativecommons.org/licenses/by/4.0/legalcode
(if CC-BY-4.0 fits the bill)

I hope that I don't need to change any word/name there.

**Comment by mekkim** [comment]
Seems like adding it to the selection list has been a requested feature for... almost 10 years now: [https://github.com/github/choosealicense.com/issues/33](https://github.com/github/choosealicense.com/issues/33)

Apparently the easiest workaround is to just pull from this repo: [https://github.com/santisoler/cc-licenses](https://github.com/santisoler/cc-licenses)

**Comment by dewan-ahmed** [comment]
Thanks for the [reference](https://github.com/santisoler/cc-licenses) @mekkim; super useful.

Will wait for your LGTM on this PR.

**Comment by mekkim** [comment]
LGTM!

**Comment by dewan-ahmed** [comment]
Fixes https://github.com/dewan-ahmed/recruiter-response-template/issues/1

**Pull request merged**
